services:
  db:
    image: postgres:16
    container_name: go-ride-db
    env_file:
      - .env
    ports:
      - "5438:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  migrate:
    image: migrate/migrate:v4.19.1
    container_name: go-ride-migrate
    depends_on:
      - db
    volumes:
      - ./migrations:/migrations
    env_file:
      - .env
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable",
        "up"
      ]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-ride-app
    env_file:
      - .env
    ports:
      - "8080:${SERVER_PORT}"
    depends_on:
      - db

volumes:
  db_data:
